### ISSUE TITLE
merging interactive.go into demo/eval.go

### ISSUE THREAD

**Issue by rocky** [0xfaded/eval#10]
How do you feel about merging _interactive.go_ into _demo/eval.go_ and thus out of the _interactive_ namespace and proper library.

My understanding is that you'll have another more feature-rich version of _interactive.go_ with code completion and real _readline_ support and that might be in a different repository.

**Comment by 0xfaded** [comment]
Yeah thats fine. I don't even like the package name 'go-interactive' anymore, but go-eval is already taken by other projects. If this nears completion, I might pinch the name.

**Comment by rocky** [comment]
I too am not enamored by the name, but I too realized _go-eval_, however appropriate, is already used elsewhere. However the namespace _eval_ is free, I think.

Whatever the name, I thing the purpose and value of this package would be to add to go an _eval()_ function. 

That may sound like a small thing, but it is not. And it opens the door to lots of other things. This one thing in of itself would make _go_ extremely powerful.
