### ISSUE TITLE
package name is wrong in "Cannot convert abc to type XXX.MyInt"

### ISSUE THREAD

**Issue by rocky** [0xfaded/eval#24]
In _callexpr_test.go_ we have 

```
    expectError(t, "bogus.MyInt(\"abc\")", &env,
    "Cannot convert abc to type eval.MyInt")
```

The error message should refer to package _bogus_, that is _bogus_.MyInt, not _eval_.MyInt . 

That error message comes from _util.go_: 

```
 return x, errors.New(fmt.Sprintf("Cannot convert %v to type %v", x, to))
```

Also note that there should be quotes around "abc". Will submit that as a separate issue.

**Comment by 0xfaded** [comment]
I think this is going to be a will not fix. Only error messages are affected, and I'm guessing the the common use case will be to create an environment that matches the compiled programs structure. Having said that, I'll keep it in mind for when I write refract and make sure new types can have their packages specified.
