### ISSUE TITLE
slice range on strings doesn't work

### ISSUE THREAD

**Issue by rocky** [0xfaded/eval#27]
Slice range doesn't work.

Here's an example:

``` console
./go-repl
=== A simple Go eval REPL ===

Results of expression are stored in variable slice "results".
The environment is stored in global variable "env".

Enter expressions to be evaluated at the "go>" prompt.

To see all results, type: "results".

To quit, enter: "quit" or Ctrl-D (EOF).
go> os.Args
Kind = slice
Type = []string
results[0] = {"./go-repl"}
go> os.Args[0][0:3]
Kind = Type = string
results[1] = "Alice"
go> 
```

**Comment by 0xfaded** [comment]
For the record Alice is a leftover placeholder for unimplemented funtionality.

**Comment by rocky** [comment]
Ah.. Ok. I've also noticed this when trying to deference pointers. 

The ssa-interpreters can't handle pointers properly. I wonder if there is going to be a similar problem here.

**Comment by 0xfaded** [comment]
no it wont be. in fact assuming a correctly type checked ast, the code
would be so trivial I'd say you should give it a shot. Id start with the
array indexing code, its a similar operation.

Carl
2014/01/05 21:58 "R. Bernstein" notifications@github.com:

**Comment by rocky** [comment]
27d1dd3ec1ce43da09be2addc34d12f0c915a828

There are these hacky CheckExpr calls: 

``` go
    if cexpr, errs = CheckExpr(ctx, e.X, env); len(errs) != 0 {
        for _, cerr := range errs {
            fmt.Printf("%v\n", cerr)
        }
        return nil, false, errors.New("Something wrong checking * expression")
    }
```
