### ISSUE TITLE
Handle array/slice indexing

### ISSUE THREAD

**Issue by rocky** [0xfaded/eval#4]
If it were done, for example, one could access previous results in which demo/eval.go saves after evaluation in the Results[] slice.

**Comment by 0xfaded** [comment]
This is not the case. If an expression evaluates to a single value, then that value is immediately available. What is really needed is a means of unpacking multiple values into single named values for future use.

**Comment by rocky** [comment]
I'm not understanding you. So let me be less abstract: 

> $ ./eval 
> ./eval 
> go> 1+2
> 1+2
> Kind = int64
> Results[0] = 3
> go> Results
> Results
> Kind = slice
> Results[1] = [3]
> go> Results[0]
> Results[0]
> Kind = string
> Results[2] = "Alice"
> go> 

See https://github.com/0xfaded/go-interactive/blob/master/expr.go#L36 where that clause is empty.

**Comment by 0xfaded** [comment]
OK, I didn't realise that results was being put back into global scope.
This will need to be done sooner or later anyway and it doesn't interfere
with my typed evaluation branch. I'll add this today

Carl
2013/12/10 11:56 "R. Bernstein" notifications@github.com:
