### ISSUE TITLE
Handle shifts

### ISSUE THREAD

**Issue by rocky** [0xfaded/eval#41]
```
go> 1 << 2
illegal constant expression: ideal << ideal
go> 
```

**Comment by rocky** [comment]
I see that there's been work on handling shifts. Looks like some tests fail though.

```
go test -i && go test
--- FAIL: TestCheckBinaryExprIntRhlInt (0.00 seconds)
    helper_for_test.go:78: Expression '4 >> 4' has type 'int', expected 'shifted_int'
--- FAIL: TestCheckBinaryExprIntRhlRune (0.00 seconds)
    helper_for_test.go:78: Expression '4 >> '@'' has type 'int', expected 'shifted_int'
--- FAIL: TestCheckBinaryExprIntRhlFloat (0.00 seconds)
    helper_for_test.go:78: Expression '4 >> 2.0' has type 'int', expected 'shifted_int'
--- FAIL: TestCheckBinaryExprRuneRhlInt (0.00 seconds)
    helper_for_test.go:78: Expression ''@' >> 4' has type 'int', expected 'shifted_int'
--- FAIL: TestCheckBinaryExprRuneRhlRune (0.00 seconds)
    helper_for_test.go:78: Expression ''@' >> '@'' has type 'int', expected 'shifted_int'
--- FAIL: TestCheckBinaryExprRuneRhlFloat (0.00 seconds)
    helper_for_test.go:78: Expression ''@' >> 2.0' has type 'int', expected 'shifted_int'
--- FAIL: TestCheckBinaryExprFloatRhlInt (0.00 seconds)
    helper_for_test.go:78: Expression '2.0 >> 4' has type 'int', expected 'shifted_int'
--- FAIL: TestCheckBinaryExprFloatRhlRune (0.00 seconds)
    helper_for_test.go:78: Expression '2.0 >> '@'' has type 'int', expected 'shifted_int'
--- FAIL: TestCheckBinaryExprFloatRhlFloat (0.00 seconds)
    helper_for_test.go:78: Expression '2.0 >> 2.0' has type 'int', expected 'shifted_int'
FAIL
exit status 1
```

**Comment by 0xfaded** [comment]
thank you for catching this. I had the tests disabled and forgot to copy
them back

Carl
2014/02/18 11:01 "R. Bernstein" notifications@github.com:

**Comment by rocky** [comment]
Well, travis would have caught this too. You need to enable the travis service hook. (And adding a status on the README.md would be nice too. But that can't be done until the service hook is enabled.)

**Comment by 0xfaded** [comment]
I'll look into it. I've was actually thinking of making an announcement
today. do a "go get "github.com/0xfaded/gack". If $GOPATH/bin is in your
$PATH you'll be able to run gack. Tell me what you think.

On Tue, Feb 18, 2014 at 9:17 AM, R. Bernstein notifications@github.comwrote:

> Well, travis would have caught this too. You need to enable the travis
> service hook. (And adding a status on the README.md would be nice too. But
> that can't be done until the service hook is enabled.)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/0xfaded/eval/issues/41#issuecomment-35335399
> .

## 

Carl

**Comment by rocky** [comment]
Didn't work for me:

$ go get "github.com/0xfaded/gack"

> 07:59:08 rocky@sanchez:~/go/src/github.com/0xfaded/eval [2,0,b] 0
> $ gack
> === A hacky Go eval REPL ===
> 
> Results of expression are stored in variable "it".
> Full and short variable declarations and assignments are supported.
> Import is also supported with limited support and a non-standard syntax.
> Multiple packages may be specified, but they can not be qualified. E.g.
> 
> ```
>     import "fmt"
>     import "pkg/a" "pkg/b" "pkg/c"
> ```
> 
> Enter expressions to be evaluated at the "go>" prompt.
> 
> To quit, enter: "quit" or Ctrl-D (EOF).
> go> import "columnize"
> Generated src failed to compile. Please file a bug report with
> /tmp/gack157274266 attached
> /tmp/gack157274266:3: import /home/rocky/go/pkg/linux_386/columnize.a:
> object is [linux 386 go1.1.1 X:none] expected [linux 386 go1.2rc5 X:none]
> exit status 1
> go>

I guess I have to rebuild columnize, but columnize otherwise works.

**Comment by 0xfaded** [comment]
Actually the issue is you need to have the .a library installed. So go
install "columnize" will fix that problem. The compile loop doesn't build
external dependencies.

Btw, the entirety of the functionality is implemented in gacklib which
could be trivially expanded to use any REPL such as go-fish. This would
require moving go-fish into a library though.

A function with the prototype Repl(env *eval.SimpleEnv, history []string)
would also be required.

On Tue, Feb 18, 2014 at 10:06 AM, R. Bernstein notifications@github.comwrote:

> Didn't work for me:
> 
> $ go get "github.com/0xfaded/gack"
> 
> > 07:59:08 rocky@sanchez:~/go/src/github.com/0xfaded/eval [2,0,b] 0
> > $ gack
> > === A hacky Go eval REPL ===
> > 
> > Results of expression are stored in variable "it".
> > Full and short variable declarations and assignments are supported.
> > Import is also supported with limited support and a non-standard syntax.
> > Multiple packages may be specified, but they can not be qualified. E.g.
> > 
> > import "fmt"
> > import "pkg/a" "pkg/b" "pkg/c"
> > 
> > Enter expressions to be evaluated at the "go>" prompt.
> > 
> > To quit, enter: "quit" or Ctrl-D (EOF).
> > go> import "columnize"
> > Generated src failed to compile. Please file a bug report with
> > /tmp/gack157274266 attached
> > /tmp/gack157274266:3: import /home/rocky/go/pkg/linux_386/columnize.a:
> > object is [linux 386 go1.1.1 X:none] expected [linux 386 go1.2rc5 X:none]
> > exit status 1
> > go>
> 
> I guess I have to rebuild columnize, but columnize otherwise works.
> 
> On Mon, Feb 17, 2014 at 7:22 PM, Carl Chatfield <notifications@github.com
> 
> > wrote:
> > 
> > I'll look into it. I've was actually thinking of making an announcement
> > today. do a "go get "github.com/0xfaded/gack". If $GOPATH/bin is in your
> > $PATH you'll be able to run gack. Tell me what you think.
> > 
> > On Tue, Feb 18, 2014 at 9:17 AM, R. Bernstein <notifications@github.com
> > 
> > > wrote:
> > > 
> > > Well, travis would have caught this too. You need to enable the travis
> > > service hook. (And adding a status on the README.md would be nice too.
> > > But
> > > that can't be done until the service hook is enabled.)
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/0xfaded/eval/issues/41#issuecomment-35335399>
> > > .
> > 
> > ## 
> > 
> > Carl
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/0xfaded/eval/issues/41#issuecomment-35335670>
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/0xfaded/eval/issues/41#issuecomment-35338662
> .

## 

Carl

**Comment by 0xfaded** [comment]
Sorry didn't quite read the entirety of your error messages. Yes, you do
have to rebuild it for the same reasons listed above.

On Tue, Feb 18, 2014 at 11:09 AM, Carl carlchatfield@gmail.com wrote:

> Actually the issue is you need to have the .a library installed. So go
> install "columnize" will fix that problem. The compile loop doesn't build
> external dependencies.
> 
> Btw, the entirety of the functionality is implemented in gacklib which
> could be trivially expanded to use any REPL such as go-fish. This would
> require moving go-fish into a library though.
> 
> A function with the prototype Repl(env *eval.SimpleEnv, history []string)
> would also be required.
> 
> On Tue, Feb 18, 2014 at 10:06 AM, R. Bernstein notifications@github.comwrote:
> 
> > Didn't work for me:
> > 
> > $ go get "github.com/0xfaded/gack"
> > 
> > > 07:59:08 rocky@sanchez:~/go/src/github.com/0xfaded/eval [2,0,b] 0
> > > $ gack
> > > === A hacky Go eval REPL ===
> > > 
> > > Results of expression are stored in variable "it".
> > > Full and short variable declarations and assignments are supported.
> > > Import is also supported with limited support and a non-standard syntax.
> > > Multiple packages may be specified, but they can not be qualified. E.g.
> > > 
> > > import "fmt"
> > > import "pkg/a" "pkg/b" "pkg/c"
> > > 
> > > Enter expressions to be evaluated at the "go>" prompt.
> > > 
> > > To quit, enter: "quit" or Ctrl-D (EOF).
> > > go> import "columnize"
> > > Generated src failed to compile. Please file a bug report with
> > > /tmp/gack157274266 attached
> > > /tmp/gack157274266:3: import /home/rocky/go/pkg/linux_386/columnize.a:
> > > object is [linux 386 go1.1.1 X:none] expected [linux 386 go1.2rc5
> > > X:none]
> > > exit status 1
> > > go>
> > 
> > I guess I have to rebuild columnize, but columnize otherwise works.
> > 
> > On Mon, Feb 17, 2014 at 7:22 PM, Carl Chatfield <notifications@github.com
> > 
> > > wrote:
> > > 
> > > I'll look into it. I've was actually thinking of making an announcement
> > > today. do a "go get "github.com/0xfaded/gack". If $GOPATH/bin is in
> > > your
> > > $PATH you'll be able to run gack. Tell me what you think.
> > > 
> > > On Tue, Feb 18, 2014 at 9:17 AM, R. Bernstein <notifications@github.com
> > > 
> > > > wrote:
> > > > 
> > > > Well, travis would have caught this too. You need to enable the travis
> > > > service hook. (And adding a status on the README.md would be nice too.
> > > > But
> > > > that can't be done until the service hook is enabled.)
> > > > 
> > > > ## 
> > > > 
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/0xfaded/eval/issues/41#issuecomment-35335399>
> > > > .
> > > 
> > > ## 
> > > 
> > > Carl
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/0xfaded/eval/issues/41#issuecomment-35335670>
> > > .
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/0xfaded/eval/issues/41#issuecomment-35338662
> > .
> 
> ## 
> 
> Carl

## 

Carl
