### ISSUE TITLE
go test: ./checkbinaryexpr_nonconst_gen_test.go:16558: invalid operation: a == b (struct containing []int cannot be compared)

### ISSUE THREAD

**Issue by rocky** [0xfaded/eval#45]
```
$ go test
# github.com/0xfaded/eval
./checkbinaryexpr_nonconst_gen_test.go:16558: invalid operation: a == b (struct containing []int cannot be compared)
FAIL    github.com/0xfaded/eval [build failed]
$ 
```

We really should add travis to the githooks.

**Comment by 0xfaded** [comment]
This is strange. I am still using go1.1 but I do do a full test run before
pushing. I'll check this tomorrow

Carl
2014/01/27 2:14 "R. Bernstein" notifications@github.com:

**Comment by 0xfaded** [comment]
Lol, go bug introduced by 1.2

Carl
2014/01/27 2:19 "Carl" carlchatfield@gmail.com:

**Comment by 0xfaded** [comment]
Spoke to soon, I misread the spec when I implemented strict comparisons,
and looks like 1.1 has the same bug.

Carl
2014/01/27 16:20 "Carl" carlchatfield@gmail.com:
