### ISSUE TITLE
^1 is not a ptr

### ISSUE THREAD

**Issue by rocky** [0xfaded/eval#47]
```
$ ./go-repl 
...
go> ^1
Kind = ptr
Type = *eval.ConstNumber
results[0] = &{Value: {Re: {a: {neg: <bool>, abs: {<big.Word>},}, b: {neg: <bool>, abs: {<big.Word>},},}, Im: {a: {neg: <bool>, abs: },}, b: {neg: <bool>, abs: },},},}, Type: int,}
go> 
```

**Comment by 0xfaded** [comment]
That's the internal  representation of consists. Try int(^1)

Carl
2014/01/27 13:32 "R. Bernstein" notifications@github.com:

**Comment by rocky** [comment]
Ok. 

> That's the internal  representation of consists.

What does this mean?

**Comment by 0xfaded** [comment]
Consts, spell checker on my phone

Carl
2014/01/27 13:59 "R. Bernstein" notifications@github.com:

**Comment by rocky** [comment]
Ok. Thanks. 

What's weird in the internal representation is that you don't see the value anywhere. 

I'm wondering if the top-level print should look for *eval.ConstNumber and show that differently? Or is there something deeper that should be done? Thoughts?

**Comment by 0xfaded** [comment]
I think that's where it belongs. I deliberately exported the const types so
that user code can defect then. The strong method on these types is
probably sufficient.

Carl
2014/01/27 14:16 "R. Bernstein" notifications@github.com:

**Comment by 0xfaded** [comment]
Inspect now has nice formatting for *ConstNumber s
