### ISSUE TITLE
A way to get a list of variables, types, and constants of a package

### ISSUE THREAD

**Issue by rocky** [0xfaded/eval#48]
Now that _Env.Pkg_ is an interface rather than a map, a way to get a list of the packages it contains, or alternatively iterate over the packages is now lacking. Similarly one may want a list of or a way to iterate over variables, types and constants in a specific package or in the environment. 

This is partly motivated by the desire to get go-fish back to the way it was before recent changes. I've had to comment out commands that list methods in a package and a list of imported packages. See for example the comment-out regions of https://github.com/rocky/go-fish/blob/get-working-again/cmd/methods.go

**Comment by 0xfaded** [comment]
The Env interface is as minimal as eval needs it. Inside go-fish, there is
nothing wrong with holding onto a reference to the *SimpleEnv or whatever
Env type you may be using.

env := MakeSimpleEnv() will achieve this.

Carl
2014/02/18 11:12 "R. Bernstein" notifications@github.com:

**Comment by 0xfaded** [comment]
As for Pkgs, if you know the Env type so just type assert

Pkgs["foo"].(*SimpleEnv)

Carl
2014/02/18 12:11 "Carl" carlchatfield@gmail.com:

**Comment by rocky** [comment]
Ok. With go-fish commit  https://github.com/rocky/go-fish/commit/b142a49442f2b82dedf33f0b69f28c1b1e025471 things are back the way they were or a little bit better. Thanks for the info.
