### ISSUE TITLE
Constants need to be evaluated as exact values

### ISSUE THREAD

**Issue by 0xfaded** [0xfaded/eval#7]
This is a thread is to track all areas code affected by improper handling of constant expressions.

integer index expressions
`a[0.5]` is not valid, whilst `a[2*0.5]` is

index of constant string expressions should generate out of bounds errors.
`"abc"[4]` is not valid

**Comment by rocky** [comment]
There are two aspects to this. First, one might catch this by checking constant expressions. 

But second, when this isn't constant there shouldn't be a _go_ panic; the evaluator should report an error as I suspect it does. Because of the issue of `Results[0]` being an interface rather than an _int64_, I can't show this in eval, but here's why I think it will panic:

```
 go> 5 + 1/0
 5 + 1/0
 panic: runtime error: integer divide by zero
```

Also:

```
 go> 1 + 5 * "a"
 1 + 5 * "a"
 eval error: invalid binary operation  ^E * a
                                       ^^! what's this? 
 go>
```

Should this be another issue to track it separately?

**Comment by 0xfaded** [comment]
Because this is an interpreter, it may make sense to run over each expression twice, first a "compile" phase which does things that would normally be done at compile phase, such as compute constants, type check, and raise `/ 0` errors, and then a "runtime" phase. 

This would have an interesting consequence that once statement evaluation is implemented, the interpreter could break on a malformed statement with previous statements in an evaluated state. For example

```
func f() int {
   a := 3
   return "abc"
}
```

would break on the return statement but `a` would already be evaluated.

Trying to think how this fits in with `EvalExprTyped`, it may be better to annotate the ast during the "compile" phase and evaluate that instead. This is getting closer to where you started with ssa. I don't like the idea of constructing an anamorphic source tree though as there may be times we want to allow the user to interact directly with the original tree.

Thoughts?

Btw I opened an issue for the `invalid binary operation` bug to keep track of all issues that should be addressed when touching error code. Now that the source tree is stored as a member of the error I will be endeavouring to match the errors given by the google go implementation.

**Comment by rocky** [comment]
I think it cleaner to do exactly as you suggest, separate type check and evaluate phases, just as the parse phase is separated from the rest. 

> I don't like the idea of constructing an anamorphic source tree though as there may be times we want to allow the user to interact directly with the original tree.

I don't understand what this means and what concern you have.

**Comment by 0xfaded** [comment]
The ssa tree is an equivalent but not a 1:1 mapping of the source tree. If we look at modern interpreted language debuggers (I know the chrome js debugger allows this) you can break execution, change the code, and then continue. If we want to be able to do something like that, I feel it would be easiest to keep the interpreted tree tied to the input ast as closely as possible.

**Comment by rocky** [comment]
Ok. No argument there.

But I'm not that religious or opinionated about it.  Yes, simple is good. Go programmers seem to obsess over speed and interpreters can be slow, even the ssa interpreter. 

If one is interested in providing real quality debugging support, one has to be able to deal with whatever one has to work with. 

So over time, I've come to grips with the many-to-many problem. (one line maps to many instruction and one instruction maps to many lines). And the speed problem - at least in my mind  as to how it can be solved. But all of this is a much longer discussion
