### ISSUE TITLE
Showing Kind (versus type) in demo/eval.go results

### ISSUE THREAD

**Issue by rocky** [0xfaded/eval#8]
Why this? 

> ```
> $ ./eval
> ./eval
> go> 1+2
> 1+2
> Kind = int64
> Results[0] = 3
> go> Results[0]
> Results[0]
> Kind = interface
> ^^^^^^^^^^^^^^^! what's this? 
> Results[1] = 3
> go> Results
> Results
> Kind = slice
> Results[2] = [3 3]
> go> Results
> Results
> Kind = slice
> Results[3] = [3 3 [3 3]]
> go>
> ```

I don't understand why this comes back _interface_ rather than some sort of _int_. And should we be showing _Kind_ or the type? Thoughts?

**Comment by rocky** [comment]
I'm pretty sure this is my fault https://github.com/0xfaded/go-interactive/blob/master/interpreter.go#L51

I converted to an _Interface()_ as a workaround so I could use the _append()_ function. I didn't understand the error message when the straight _reflect.Value_ was in there.

**Comment by 0xfaded** [comment]
I think I would find knowing both the kind and type useful when playing with third party libraries. Up to you though

**Comment by rocky** [comment]
_type_ information is a superset of _kind_ isn't it?

**Comment by 0xfaded** [comment]
Well, strictly speaking a type is a set of values, and a kind is a set of types. So yes, information about a type could also imply it's kind. But for practical purposes, I would like to see something like

```
type = Named(int)
```

for named types.

**Comment by rocky** [comment]
This is now done in the demo code in those cases where Kind is not the same thing as Type.
