### ISSUE TITLE
Improve old errors

### ISSUE THREAD

**Issue by 0xfaded** [0xfaded/eval#9]
before commit 158e05a error messages where rather crude.

Below are issues that should be attended to when redoing old error code.

```
 go> 1 + 5 * "a"
 1 + 5 * "a"
 eval error: invalid binary operation  ^E * a
                                       ^^! what's this? 
 go>
```

**Comment by rocky** [comment]
Also the unquoted _a_ is weird. This again is my doing when I stripped the quotes from [basiclitexpr.go](https://github.com/0xfaded/go-interactive/blob/master/basiclitexpr.go#L25). I realized this would "break" places that expected strings to be shown with the quotes. 

In the back of my mind I had that the right way to handle all of this is to add a _String()_ method which add would back. For example https://github.com/0xfaded/go-interactive/blob/master/interpreter.go#L45-L46 would use that _String()_ method.

**Comment by 0xfaded** [comment]
The real issue here is that these old errors use `Printf("%s", reflect.Value)`, the new errors use a substring of the actual input which will include the entire lit verbatim.
